/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_interface_brouart;

/**
 *
 * @author Asus
 */
public class Fenetre_Principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre_Principale
     */
    public Fenetre_Principale() {
        initComponents();
        resultat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        Bouton_valider = new javax.swing.JButton();
        zonenom = new javax.swing.JTextField();
        nomentrée = new javax.swing.JLabel();
        resultat = new javax.swing.JLabel();
        salaireentree = new javax.swing.JLabel();
        zonesalaire = new javax.swing.JTextField();
        bouton_augmenter = new javax.swing.JButton();
        bienvenue = new javax.swing.JLabel();
        richesse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setBackground(new java.awt.Color(204, 153, 0));
        titre.setFont(new java.awt.Font("Segoe UI Emoji", 2, 48)); // NOI18N
        titre.setForeground(new java.awt.Color(0, 0, 255));
        titre.setText("CPO");

        Bouton_valider.setBackground(new java.awt.Color(255, 255, 153));
        Bouton_valider.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bouton_valider.setText("Valider");
        Bouton_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_validerActionPerformed(evt);
            }
        });

        zonenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonenomActionPerformed(evt);
            }
        });

        nomentrée.setText("Entrez votre prénom");

        salaireentree.setText("Entrez votre salR");

        bouton_augmenter.setBackground(new java.awt.Color(51, 204, 0));
        bouton_augmenter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bouton_augmenter.setForeground(new java.awt.Color(0, 51, 0));
        bouton_augmenter.setText("Augmenter SalR");
        bouton_augmenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_augmenterActionPerformed(evt);
            }
        });

        bienvenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bienvenue.setText("Bienvenue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salaireentree, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(zonesalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomentrée, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zonenom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bouton_augmenter)
                                .addGap(18, 18, 18)
                                .addComponent(richesse, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bouton_valider)
                                .addGap(38, 38, 38)
                                .addComponent(bienvenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomentrée)
                    .addComponent(zonenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bouton_valider)
                    .addComponent(bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaireentree)
                    .addComponent(zonesalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouton_augmenter)
                    .addComponent(richesse, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_validerActionPerformed
        // TODO add your handling code here:
        String a = zonenom.getText();
        bienvenue.setText("salam "+ a);
        //resultat.setVisible(true);
    }//GEN-LAST:event_Bouton_validerActionPerformed

    private void zonenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zonenomActionPerformed

    private void bouton_augmenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_augmenterActionPerformed
        // TODO add your handling code here:
        String salaire = zonesalaire.getText();
        int salaire_entier = Integer.parseInt(salaire);
        salaire_entier++;
        zonesalaire.setText(salaire_entier+"");
        richesse.setText(salaire_entier+" € la kichta s'aggrandit !!!!");
    }//GEN-LAST:event_bouton_augmenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_valider;
    private javax.swing.JLabel bienvenue;
    private javax.swing.JButton bouton_augmenter;
    private javax.swing.JLabel nomentrée;
    private javax.swing.JLabel resultat;
    private javax.swing.JLabel richesse;
    private javax.swing.JLabel salaireentree;
    private javax.swing.JLabel titre;
    private javax.swing.JTextField zonenom;
    private javax.swing.JTextField zonesalaire;
    // End of variables declaration//GEN-END:variables
}
